# Generated by Django 5.2.5 on 2025-08-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='auther',
            new_name='author',
        ),
    ]
